# Generated by Django 5.2.4 on 2025-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BogieChecksheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspector_name", models.CharField(max_length=100)),
                ("remarks", models.TextField()),
                ("date_checked", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="WheelSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspector_name", models.CharField(max_length=100)),
                ("form_number", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="wheel_specs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
